import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/Context/AuthContext";
import Navbar from "@/components/Containers/Navbar";
import Home from "../components/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          {children}
      </body>
    </html>
  );
}
